---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "30"
year: "2016"
contributor: 
- "Andreas Hartsch"
title: "Das Hybride als Normalität. Digitaler Wandel und analoge Herkunftswelten"
abstract: "Diskursanalytisch untersucht werden konzeptionelle Verunsicherungen bei
der Medienausrichtung von Bibliotheken, die von einer unsteten, auf
Durchsetzungserfolge bauenden Orientierung an unbewiesenem
Gleichzeitigen oder Zukünftigen herzurühren scheinen. Dabei gerät
Bewiesenes unter Begründungszwänge und Verdrängungsdruck. Paradigmatisch
dafür wird der Satz ausgemacht: 'Das Neue ist das Gute', von dem eine
Steigerungsform, nun unter gänzlichem Verzicht auf Qualitätsurteile
existiert: 'Das Neue ist das Selbstverständliche'. Das wird hier
hinterfragt mit transdisziplinärem Blick auf Diskussionsbeiträge
hauptsächlich aus 2014 bis 2016. Herausgearbeitet wird ein
informationswissenschaftliches Plädoyer für Mediensymbiosen aller Art,
auf die das hybride Bibliotheksverständnis - in den
Geisteswissenschaften zumal - selbstredend seit Jahrzehnten zu Recht
aufsetzt und dessen Verstetigung dringend empfohlen wird."
urn: "urn:nbn:de:kobv:11-100244137"
date: 2016-12-19 18:00
comments: false
sharing: true
footer: true

---