---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "30"
year: "2016"
contributor: 
- "Karsten Schuldt"
title: "Rezension zu: Smiljana Antonijević (2015). <i>Amongst Digital Humanists: An Ethnographic Study of Digital Knowledge Production</i>. Basingstoke ; New York : Palgrave Macmillan"
comments: false
sharing: true
footer: true

---
