---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "30"
year: "2016"
contributor: 
- "Torsten Roeder"
title: "Daten auf Wanderschaft"
subtitle: "Migration von Daten als Herausforderung der Digital Humanities am Beispiel von MUSICI und MusMig"
date: 2016-12-19 18:00
urn: "urn:nbn:de:kobv:11-100244161"
comments: false
sharing: true
footer: true

---