---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "30"
year: "2016"
contributor: 
- "Ben Kaden"
title: "Bibliothek und Poesie"
subtitle: "Rezension zu: Raymund Dittrich (Hrsg.) (2016): <i>Bibliothek der Dichter. Eine Auswahl deutschsprachiger Bibliotheksgedichte vom 16. Jahrhundert bis in die Gegenwart</i>. Leipzig: Engelsdorfer Verlag."
comments: false
sharing: true
footer: true

---