---
layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "30"
year: "2016"
contributor: 
- "Redaktion LIBREAS"
title: "Editorial #30: Post-Digital Humanities"
date: 2016-12-22 13:00
comments: false
sharing: true
footer: true
---
