---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "30"
year: "2016"
contributor: 
- "Thomas Ernst"
title: "Eine Kritik der Kritik des Open Access"
subtitle: "Zu den Debatten über das Zweitveröffentlichungsrecht und über die Wertigkeit von Print- vs. Digitalpublikationen in den Geisteswissenschaften"
date: 2016-12-14 18:00
comments: false
sharing: true
footer: true

---
