---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "30"
year: "2016"
contributor: 
- "Eric W. Steinhauer"
title: "Die Nutzung einer 'Schattenbibliothek' im Licht des Urheberrechts"
abstract: "Nachveröffentlichung von <https://ub-deposit.fernuni-hagen.de/receive/mir_mods_00000825> / CC-BY"
date: 2016-12-14 18:00
comments: false
sharing: true
footer: true

---
