---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "30"
year: "2016"
contributor: 
- "Sandra Balck"
title: "(X)Disziplinarität der Informationswissenschaft"
abstract: "In zahlreichen informationswissenschaftlichen Texten wird auf die
x-disziplinäre Ausrichtung der Disziplin hingewiesen. Der Beitrag
befasst sich mit wissenschaftstheoretischen und -soziologischen
Bedingungen disziplin- und systemübergreifender Zusammenarbeit und
Vernetzung. Der Schwerpunkt liegt auf der Informationswissenschaft als
„Wissenschaft der Information“ und ihrer Aufgabe/Bedeutung in Zeiten
stetig wachsender und unüberschaubar werdender Informations- und
Wissensbestände. Ausgehend von einer allgemeinen Einordnung von
Wissenschaft und das durch sie hervorgebrachte Wissen, werden die
Voraussetzungen für eine systematische Ordnung der modernen Wissenschaft
und die daraus resultierende Notwendigkeit x-disziplinärer Kooperation
dargestellt. Es folgt eine disziplinäre Verortung der
Informationswissenschaft innerhalb des wissenschaftlichen Systems; neben
dem Begriff der Information wird die paradigmatische Entwicklung der
Informationswissenschaft skizziert. Durch Auswertung einschlägiger
Publikationen, Gegenüberstellung und diskursiver Einordnung der
themenspezifischen (impliziten sowie expliziten) Stellungnahmen wird,
darauf aufbauend, der x-disziplinäre Fachdiskurs der
Informationswissenschaft dargestellt."
urn: "urn:nbn:de:kobv:11-100244141"
date: 2016-12-19 18:00
comments: false
sharing: true
footer: true

---