---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "30"
year: "2016"
contributor: 
- "Juliane Waack"
title: "Die Bibliografie von New Orleans. Zu einem Gedicht"
urn: "urn:nbn:de:kobv:11-100244223"
comments: false
sharing: true
footer: true

---
