---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "30"
year: "2016"
contributor: 
- "Dorothea Kühnlein" 
- "Mareen Reichardt"
title: "Rahmenbedingungen für das Publizieren eines Open-Access-Journals. Ein Szenario"
abstract: "Inspiriert von den Erfahrungen aus dem DFG-Projekt 'Future Publications
in den Humanities' werden auf Grundlage eines gegebenen fiktiven
Szenarios für das Publizieren eines geisteswissenschaftlichen
Open-Access-Journals die verschiedenen Strategien und Möglichkeiten des
Open Access erörtert. Als mögliche Option wird zum einen der Grüne Weg
mit der Weiterführung der Printausgabe über den alten Verlag und dem
Open-Access-Publizieren der Artikel auf einem Repositorium
identifiziert. Weiterhin kann der hybride Goldene Weg herausgestellt
werden, mit der Möglichkeit über einen neuen Verlag die Printausgabe um
eine elektronische Parallelausgabe zu erweitern und einzelne Artikel im
Open-Access-Verfahren bereitzustellen. Auch der Goldene Weg im
Selbstverlag wird als Alternative erläutert. Es werden jeweils die Vor-
und Nachteile aller Optionen abgewogen."
date: 2016-12-14 18:00
comments: false
sharing: true
footer: true

---
