---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "30"
year: "2016"
contributor: 
  - "Ben Kaden"
title: "Notiz zum Cover der LIBREAS-Ausgabe 30 - Frieden"
urn: "urn:nbn:de:kobv:11-100244129"
comments: false
sharing: true
footer: true

---