---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "30"
year: "2016"
contributor: 
- "Ingo Frank"
title: "Fortschritt durch Rückschritt &mdash; vom Bibliothekskatalog zum Denkwerkzeug"
subtitle: "Eine Idee"
abstract: "Der Text zeigt anhand einer essayistisch selektiven Rückschau in die Zeit vor den
Digital Humanities bibliotheks- und informationswissenschaftliche Ansätze zur
Entwicklung hypertextueller Werkzeuge für Bibliographie-Verwaltung und Strukturierung
des wissenschaftlichen Diskurses - eine zukunftsweisende Idee für eine
digitale Geisteswissenschaft zur Unterstützung geisteswissenschaftlicher Denkarbeit
jenseits von reinem 'distant thinking'."
date: 2016-12-14 18:00
comments: false
sharing: true
footer: true

---
