---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "30"
year: "2016"
contributor: 
- "Jens Wonke-Stehle"
title: "Rezension zu: Ulrich Herb (2015). <i>Open Science in der Soziologie: Eine interdisziplinäre Bestandsaufnahme zur offenen Wissenschaft und eine Untersuchung ihrer Verbreitung in der Soziologie</i>. Glückstadt: vwh."
comments: false
sharing: true
footer: true

---
